apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-dev-envs
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
          - env: staging
            namespace: staging
  template:
    metadata:
      name: "myapp-{{env}}"
    spec:
      project: dev
      source:
        repoURL: https://github.com/edenbarkan/helm-charts.git
        targetRevision: main
        path: charts/generic-app
        helm:
          valueFiles:
            - ../../apps/myapp/base/values.yaml
            - ../../apps/myapp/overlays/{{env}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
